### ISSUE TITLE
[Bug] The title don't scroll

### ISSUE THREAD

**Issue by cxmmunist** [CreArts-Community/Friends-Grid#10]
![ShareX_yNKz5N5wNo](https://user-images.githubusercontent.com/72283516/151257599-7ec7329d-fdc0-4d5c-b409-a5aa00f58aff.png)
![DiscordCanary_kX8vw2de5I](https://user-images.githubusercontent.com/72283516/151257604-f2dd8d5d-4a27-43ae-825c-fa8ad1b25193.png)
ive tried with every plugin and theme BUT friends grid disabled, and it still does it.. might just be discord fault, idfk.

**Comment by CorellanStoma** [comment]
Hi, thanks for the message, it's currently really annoying with all the daily discord changes to the friends list. I have uploaded a new version and the problem should be fixed now.

**Comment by cxmmunist** [comment]
Thank you!
