### ISSUE TITLE
[Bug] No banner

### ISSUE THREAD

**Issue by Luna-devv** [CreArts-Community/Friends-Grid#6]
Hey there,
When I am using this theme it doesn't display the users banner in the friends list as you can see in the [screenshot](https://cdn.xyna.space/kua2jfip69a) below.
> https://cdn.xyna.space/kua2jfip69a

~ Luni

**Comment by fleazz** [comment]
this is also happening to me

**Comment by Loremly** [comment]
Banners were never in the friend's list to begin with, so duplicating banners from users onto the friend grid would require JS.

**Comment by Luna-devv** [comment]
@Loremly Then why is there a user banner on the product image when it's not in the downloadable Theme?

![image](https://user-images.githubusercontent.com/71079641/144120320-7185363c-e031-41ff-91c4-260ec93adb80.png)

**Comment by Loremly** [comment]
Idk ask Corellan. Companies always put things in ads that aren't in the actual product.

**Comment by CorellanStoma** [comment]
@Luna-devv At that time I had a plugin loaded for this when I took the screenshot, I had forgotten to deactivate it, I will correct this on occasion.

**Comment by Luna-devv** [comment]
Hey @CorellanStoma, ah okey - I didn’t know that this is an extra plugin..
Also is this plugin available to download?

**Comment by Davr1** [comment]
@Luna-devv [https://github.com/hyblocker/discord-theme-helper](https://github.com/hyblocker/discord-theme-helper)

**Comment by vozoid** [comment]
you can edit the css by replacing activity-card-background with activity-card in the themes config thing
