### ISSUE TITLE
[Bug] Grid order messed up (BetterDiscord?)

### ISSUE THREAD

**Issue by cxmmunist** [CreArts-Community/Friends-Grid#9]
might just be me, but the grid order is messed up..
![image](https://user-images.githubusercontent.com/72283516/150667929-5bb993b0-ee18-4282-ac76-20c0e6eb64ed.png)
this is with all themes and plugins turned off

**Comment by CorellanStoma** [comment]
Hmm do you have the newest version? Everything works normal for me.
![image](https://user-images.githubusercontent.com/58918358/150668304-0e8f6ce2-4cbb-4a1c-a57f-cfd1bc920c41.png)

**Comment by cxmmunist** [comment]
Yes, i have it imported.
Its supposed to be 2 cards at a time, it usually is for me on laptop.
Its also wayy too close for some reason,,
i can fix the too close issue myself but idk how to fix the only 1 card lel

**Comment by CorellanStoma** [comment]
Well I'm not quite sure, but I think the problem with the grid and the search bar are somehow related.

It seems that some clients have different classes than others, despite having the same version.
![image](https://user-images.githubusercontent.com/58918358/150702758-eea31c31-4942-40c1-ba4c-002a9674d112.png)

**Comment by CorellanStoma** [comment]
![image](https://user-images.githubusercontent.com/58918358/150703134-74d40822-b642-4e8a-a09f-8883f329de85.png)

**Comment by CorellanStoma** [comment]
I published a new version, it should be fixed now:
https://github.com/CreArts-Community/Friends-Grid/releases/tag/v1.0.8

**Comment by cxmmunist** [comment]
it is! ty
